name: biton_ai
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.4.3
  intl: 0.17.0
#  firebase_ui_auth:
  google_fonts: ^4.0.3
  omni_datetime_picker: ^0.1.4
  http: ^0.13.5
  flutter_typeahead: ^4.3.1
  autocomplete_textfield: ^2.0.1
  hive: ^2.2.3
  path_provider: ^2.0.13
  share: ^2.0.4
  url_launcher: ^6.1.10
  haversine_distance: ^1.2.1
  dio: ^5.0.1
  #  flutter_svg: ^1.1.6
  flutter_svg: ^2.0.6
  collection: ^1.16.0
  firebase_analytics: ^10.1.5
  share_plus: ^6.3.1
  widgets_to_image: ^0.0.2
  mixpanel_flutter: ^2.1.1
  rich_console: ^1.0.4
  shared_preferences: ^2.1.0
  flutter_screenutil: ^5.7.0
  entry: ^0.0.8+1
  shimmer: ^2.0.0
  super_editor: ^0.1.0
  quill_html_editor: ^2.0.7
  html_editor_enhanced: ^2.5.1
  curved_progress_bar: ^1.0.2
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  flutter_dotenv: ^5.0.2
  intl_phone_field: ^3.1.0
  firebase_auth: ^4.6.2
  sentry_flutter: ^7.6.2
  characters: ^1.2.1
  google_sign_in: ^6.1.3
  flutter_auth_ui: ^3.1.0
  encrypt: ^5.0.1
  flutter_web_auth: ^0.5.0
  translator: ^0.1.7
  google_cloud_translation: ^0.0.3
#  text_selection_controls: ^0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_annotation:
  json_serializable: ^6.3.1
  flutter_gen_runner: ^5.1.0+1
  freezed: ^2.1.0+1


  flutter_launcher_icons: 0.11.0
  #  flutter_launcher_name: ^0.0.1
  #  flutter_launcher_name: # flutter pub get

  # flutter pub run flutter_launcher_icons:main
  # "WARNING: Icons with alpha channel are not allowed in the Apple App Store.
  # Set "remove_alpha_ios: true" to remove it."
flutter_icons:
  ios: true
#  android: "ic_launcher"
#  image_path: "assets/wtsp-green-app_icon.png"

flutter_gen:
  output: lib/common/
  integrations:
    flutter_svg: true

flutter:
  assets:
    - assets/
    - assets/svg/
#    - .env
#    - assets/covers/
  uses-material-design: true