// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbIPFyvK4xBe3U-uQh66pGeMsGunCH3Yo',
    appId: '1:1070132561841:web:53d36c49d8030e13499f90',
    messagingSenderId: '1070132561841',
    projectId: 'textstore-ai',
    authDomain: 'textstore-ai.firebaseapp.com',
    storageBucket: 'textstore-ai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7SdzYohGLZXPczeebt3udSd2zoXIRGkg',
    appId: '1:1070132561841:android:a0e45f9f791e21ca499f90',
    messagingSenderId: '1070132561841',
    projectId: 'textstore-ai',
    storageBucket: 'textstore-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKaKn9KymUK50tj_eweSd_pWtQ1JoMv88',
    appId: '1:1070132561841:ios:1dc6510b446fdd7b499f90',
    messagingSenderId: '1070132561841',
    projectId: 'textstore-ai',
    storageBucket: 'textstore-ai.appspot.com',
    iosClientId: '1070132561841-ag78t9205talpf5b0d33s5oupbr0qn7a.apps.googleusercontent.com',
    iosBundleId: 'com.biton.ai.bitonAi',
  );
}
